### ISSUE TITLE
[Thank You] design refiment

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#126]

**Comment by roughprada** [comment]
@yoavaviram can you add some of the requirements here?

**Comment by roughprada** [comment]
@yoavaviram What I mean with refinements is just your concerns on this screen based on the feedback we had.

**Comment by yoavaviram** [comment]
Here is my wishlist of what I'd like to show on this page, not in priority order:

1. Request for donation
2. Request for Social sharing
3. Request the for the user to enter their email so that we can send him a reminder after 30 days to escalate to the DPA, and optionally to subscribe to our newsletter
4. A note explaining what happens next in terms of the legal process (company may ask for additional info etc, and how to escalate)
5. A note explaining what to do if email client was not opened

I call this a wish list since I don't think it can all fit in.
